baseURL = "/"
languageCode = "en-us"
title = "Piklist Documentation"
publishDir = "docs"
canonifyURLs = true
enableGitInfo = true
theme = "piklist-theme"
googleAnalytics = "UA-31864921-2"
pygmentsUseClasses = true
pluralizelisttitles = false
[outputs]
  home = ["HTML", "RSS", "JSON"]
[markup.goldmark.renderer]
  unsafe= true
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 4
[Social]
  twitter = "piklist"
relativeURLs = true
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
